spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 231126
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
