package com.example.demo.pojo;

import lombok.ToString;

@ToString
public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stud_name
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    private String studName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    private Integer grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stud_name
     *
     * @return the value of student.stud_name
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    public String getStudName() {
        return studName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stud_name
     *
     * @param studName the value for student.stud_name
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    public void setStudName(String studName) {
        this.studName = studName == null ? null : studName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade
     *
     * @return the value of student.grade
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade
     *
     * @param grade the value for student.grade
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }
}
