package com.example.demo.mapper;

import com.example.demo.pojo.StudentCourseRelationship;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StudentCourseRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_relationship
     *
     * @mbggenerated Fri Oct 14 01:21:17 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_relationship
     *
     * @mbggenerated Fri Oct 14 01:21:17 CST 2022
     */
    int insert(StudentCourseRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_relationship
     *
     * @mbggenerated Fri Oct 14 01:21:17 CST 2022
     */
    int insertSelective(StudentCourseRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_relationship
     *
     * @mbggenerated Fri Oct 14 01:21:17 CST 2022
     */
    StudentCourseRelationship selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_relationship
     *
     * @mbggenerated Fri Oct 14 01:21:17 CST 2022
     */
    int updateByPrimaryKeySelective(StudentCourseRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course_relationship
     *
     * @mbggenerated Fri Oct 14 01:21:17 CST 2022
     */
    int updateByPrimaryKey(StudentCourseRelationship record);

    /**
     *  根据学生id查询对应的关联关系
     */
    List<StudentCourseRelationship> selectByStudentId(Long studentId);

    /**
     *  根据课程id查询对应的关联关系
     */
    List<StudentCourseRelationship> selectByCourseId(Long courseId);
}
