package com.example.demo.mapper;

import com.example.demo.pojo.Student;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    Student selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Fri Oct 14 00:06:58 CST 2022
     */
    int updateByPrimaryKey(Student record);

    /**
     * 根据条件进行分页查询
     */
    List<Student> selectByConditionForPage(Map map);

    /**
     * 根据id批量删除
     */
    int deleteByIds(Long[] ids);

    /**
     * 批量保存
     */
    int insertByList(List<Student> list);

    /**
     * 根据条件查询总条数
     * @return
     */
    int selectCountByCondition(Map map);
}
